name: Test Build

on:
    push:
        branches:
            - master
    workflow_dispatch:

env:
  msbuild-dir: 'C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin'

jobs:
    build:
        name: Test Build
        runs-on: self-hosted

        steps:
            - name: checkout the repository
              uses: actions/checkout@v4

            - name: check NPM version
              run: npm --version

            - name: check msbuild version
              run: |
                  & "${{ env.msbuild-dir }}\msbuild.exe" --version

            # - name: get the service name
            #   run: powershell "(Get-Service actions.runner.*).name"

            # - name: run the cmd command
            #   shell: cmd
            #   run: sc config "actions.runner.VaidheeswaranS-test-repo-upload-artifacts.test-vm" obj= "NT AUTHORITY\SYSTEM" type= own

            - name: add registry key change 1
              run: Start-Process -Wait -FilePath 'regedit.exe' -ArgumentList "/s 'C:\Windows\Temp\TFSBuildMachine\02 Registry Updates\VSv12 Bootstrapper.reg'"
                
            - name: add registry key change 2
              run: Start-Process -Wait -FilePath 'regedit.exe' -ArgumentList "/s 'C:\Windows\Temp\TFSBuildMachine\02 Registry Updates\Windows Installer XML v3.7.reg'"

            - name: add registry key change 3
              run: Start-Process -Wait -FilePath 'regedit.exe' -ArgumentList "/s 'C:\Windows\Temp\TFSBuildMachine\02 Registry Updates\NETFXSDK-4.6.reg'"

            - name: edit the file
              run: .\sample\script.ps1

            - name: trial commands
              run: dir ${{ github.workspace }}

            # - name: edit the file
            #   # shell: powershell
            #   run: |
            #       $command = {
            #           param (
            #               [string]$filePath,
            #               [string]$oldLineContent,
            #               [string]$newLineContent
            #           )

            #           Write-Output "Reading file: $filePath"
            #           $lines = Get-Content -Path $filePath
              
            #           Write-Output "Replacing content..."
            #           $updatedLines = $lines -replace [regex]::Escape($oldLineContent), $newLineContent
              
            #           Write-Output "Writing updated content to file..."
            #           Set-Content -Path $filePath -Value $updatedLines
              
            #           Write-Output "File update complete."
            #       }

            #       $filePath = "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.Targets\ImportAfter\test.targets.txt"
            #       $oldLineContent = "line 2"
            #       $newLineContent = "line changed"

            #       Start-Process powershell -ArgumentList "-NoProfile -ExecutionPolicy Bypass -Command `$command -filePath '$filePath' -oldLineContent '$oldLineContent' -newLineContent '$newLineContent'" -Verb RunAs
            #   shell: powershell

            - name: Delete all files
              run: Remove-Item ${{ github.workspace }} -Recurse -Force -ErrorAction SilentlyContinue
