name: Upload Artifacts

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Make the files ready
        run: |
          find sample/ -type f -name "*.dll" -o -name "*.exe" -o -name "*.msi" -exec cp {} /tmp/ \;
          tar -czf artifacts.tar.gz -C /tmp .
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: artifacts.tar.gz
