name: Upload Artifacts

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EXTENSIONS: ".dll .exe .msi"
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Print current working directory
        run: pwd

      - name: Creating a folder for artifacts
        run: mkdir temp/

      - name: Listing the location to check if the folder is created
        run: ls -l

      - name: Find and copy the files
        run: |
          IFS=' ' read -ra EXT_ARRAY <<< "$EXTENSIONS"
          for EXT in "${EXT_ARRAY[@]}"; do
            find sample/ -type f -name "*$EXT" -exec cp {} temp/ \;
          done

      - name: Listing the temp folder
        run: |
          cd temp/
          ls -la

      - name: Upload artifacts to blob storage
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: temp
          container_name: binaries
          connection_string: ${{ secrets.ConnectionString }}
          overwrite: 'true'

      - name: Listing the temp folder once artficats are pushed to blob storage
        run: |
          cd temp/
          ls -la      

      # - name: Uploading artifacts to azure storage account
      #   uses: azure/CLI@v1
      #   with:
      #     azcliversion: 2.0.72
      #     inlineScript: |
      #       az storage blob upload-batch --source temp/* --destination binaries --account-name vaidheestorageacc --sas-token ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: my-artifact
      #     path: temp/
