name: Upload Artifacts

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EXTENSIONS: ".dll .exe .msi"
      COPY_COMMAND: 'find sample/ -type f \( -name "{}" \) -exec cp -v {} temp/ \\;'
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Print current working directory
        run: pwd

      - name: Creating a folder for artifacts
        run: mkdir temp/

      - name: Listing the location to check if the folder is created
        run: ls -l

      - name: Find and copy the files
        run: |
          IFS=' ' read -ra EXT_ARRAY <<< "$EXTENSIONS"
          for EXT in "${EXT_ARRAY[@]}"; do
            eval "$COPY_COMMAND"
          done

      - name: Listing the temp folder
        run: |
          cd temp/
          ls -la

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: temp/
