name: Upload Artifacts

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EXTENSIONS: ".dll .exe .msi"
    
    steps:
      - name: Checout the repository
        uses: actions/checkout@v3

      - name: Print current working directory
        run: pwd

      - name: Creating a folder for artifacts
        run: mkdir temp/

      - name: Listing the location to check if the folder is created
        run: ls -l

      - name: Find and copy the files
        run: |
          IFS=' ' read -ra EXT_ARRAY <<< "$EXTENSIONS"
          for EXT in "${EXT_ARRAY[@]}"; do
            find sample/ -type f -name "*$EXT" -exec cp {} temp/ \;
          done

      - name: Listing the temp folder
        run: |
          cd temp/
          ls -la

      # Using SAS connection string to upload the artifacts to Blob Storage
      
      - name: Upload artifacts to blob storage
        uses: bacongobbler/azure-blob-storage-upload@v2.0.1
        with:
          source_dir: temp
          container_name: binaries
          connection_string: ${{ secrets.ConnectionString }}
          overwrite: 'true'

      - name: Listing the temp folder once artficats are pushed to blob storage
        run: |
          cd temp/
          ls -la

      # Uploading the artifacts to GitHub artifacts instead of sending to Azure Blob Storage
      
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: my-artifact
      #     path: temp/
