name: Upload Artifacts

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Print current working directory
        run: pwd

      - name: Creating a folder for artifacts
        run: mkdir temp/

      - name: Listing the location to check if the folder is created
        run: ls -l

      # - name: Find and copy the files
      #   run: |
      #     find sample/ -type f -name "*.dll" -o -name "*.exe" -o -name "*.msi" -exec cp -v {} temp \;
      #     tar -czf artifacts.tar.gz -C /tmp .
      #   shell: bash

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: my-artifact
      #     path: artifacts.tar.gz
