name: Upload Artifacts

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EXTENSIONS: ".dll .exe .msi"
    
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Print current working directory
        run: pwd

      - name: Creating a folder for artifacts
        run: mkdir temp/

      - name: Listing the location to check if the folder is created
        run: ls -l

      - name: Find and copy the files
        run: |
          IFS=' ' read -ra EXT_ARRAY <<< "$EXTENSIONS"
          for EXT in "${EXT_ARRAY[@]}"; do
            find sample/ -type f -name "*$EXT" -exec cp {} temp/ \;
          done

      - name: Listing the temp folder
        run: |
          cd temp/
          ls -la

      # Using Azure Service Pricipal to upload the artifacts to Blob Storage
      
      - name: Upload artifacts to azure blob storage using service principal
        uses: azure/CLI@v1
        with:
          azcliversion: 2.34.0
          inlineScript: |
            az storage blob upload-batch --account-name vaidheestorageacc --auth-mode key -d 'binariessecondary' -s temp/*

      # Using SAS token to upload the artifacts to Blob Storage
      
      # - name: Upload artifacts to blob storage
      #   uses: bacongobbler/azure-blob-storage-upload@main
      #   with:
      #     source_dir: temp
      #     container_name: binaries
      #     connection_string: ${{ secrets.ConnectionString }}
      #     overwrite: 'true'

      - name: Listing the temp folder once artficats are pushed to blob storage
        run: |
          cd temp/
          ls -la

      # Uploading the artifacts to GitHub artifacts instead of sending to Azure Blob Storage
      
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: my-artifact
      #     path: temp/
